const parkings = [
  {
    locationId: 1,
    location: "Chennai Mall 1",
    floors: [
      {
        floorId: 1,
        name: "Floor 1",
        slots: [
          { id: 1, slotName: "Slot 1", occupied: true, user: "User1", userVehicleNo: "TN/07/AB/1234", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 2, slotName: "Slot 2", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 3, slotName: "Slot 3", occupied: true, user: "User2", userVehicleNo: "TN/07/AB/5678", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 4, slotName: "Slot 4", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 5, slotName: "Slot 5", occupied: false, user: null, userVehicleNo: null, reserved: true, 
            reservedDetail: [{
              plan:"shortTerm",
              startDate:"2026-04-18",
              endDate:"",
              startTime:"",
              endTime:"",
              user:"1",
              userVehicleNo:"TN/07/AB/1234"
            }]
            , occupiedDt: null },
          { id: 6, slotName: "Slot 6", occupied: true, user: "User3", userVehicleNo: "TN/07/AB/9012", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 7, slotName: "Slot 7", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 8, slotName: "Slot 8", occupied: true, user: "User4", userVehicleNo: "TN/07/AB/3456", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 9, slotName: "Slot 9", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 10, slotName: "Slot 10", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 11, slotName: "Slot 11", occupied: true, user: "User5", userVehicleNo: "TN/07/AB/7890", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 12, slotName: "Slot 12", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 13, slotName: "Slot 13", occupied: true, user: "User6", userVehicleNo: "TN/07/AB/2345", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 14, slotName: "Slot 14", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 15, slotName: "Slot 15", occupied: false, user: null, userVehicleNo: null, reserved: true, 
             reservedDetail: [{
              plan:"longTerm",
              startDate:"2026-04-20",
              endDate:"2026-04-25",
              startTime:"",
              endTime:"",
              user:"1",
              userVehicleNo:"TN/07/AB/1234"
            }]
            , occupiedDt: null },
          { id: 16, slotName: "Slot 16", occupied: true, user: "User7", userVehicleNo: "TN/07/AB/6789", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 17, slotName: "Slot 17", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 18, slotName: "Slot 18", occupied: true, user: "User8", userVehicleNo: "TN/07/AB/1122", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 19, slotName: "Slot 19", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 20, slotName: "Slot 20", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
        ],
      },
      {
        floorId: 2,
        name: "Floor 2",
        slots: [
          { id: 1, slotName: "Slot 1", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 2, slotName: "Slot 2", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 3, slotName: "Slot 3", occupied: true, user: "User2", userVehicleNo: "TN/07/AB/5678", reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 4, slotName: "Slot 4", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 5, slotName: "Slot 5", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 6, slotName: "Slot 6", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 7, slotName: "Slot 7", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 8, slotName: "Slot 8", occupied: true, user: "User4", userVehicleNo: "TN/07/AB/3456",reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 9, slotName: "Slot 9", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 10, slotName: "Slot 10", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 11, slotName: "Slot 11", occupied: true, user: "User5", userVehicleNo: "TN/07/AB/7890" ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 12, slotName: "Slot 12", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 13, slotName: "Slot 13", occupied: true, user: "User6", userVehicleNo: "TN/07/AB/2345" ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 14, slotName: "Slot 14", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 15, slotName: "Slot 15", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 16, slotName: "Slot 16", occupied: true, user: "User7", userVehicleNo: "TN/07/AB/6789" ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 17, slotName: "Slot 17", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 18, slotName: "Slot 18", occupied: true, user: "User8", userVehicleNo: "TN/07/AB/1122" ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 19, slotName: "Slot 19", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 20, slotName: "Slot 20", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
        ],
      },
      {
        floorId: 3,
        name: "Floor 3",
        slots: [
          { id: 2, slotName: "Slot 2", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 1, slotName: "Slot 1", occupied: true, user: "User1", userVehicleNo: "TN/07/AB/1234",reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 4, slotName: "Slot 4", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 3, slotName: "Slot 3", occupied: true, user: "User2", userVehicleNo: "TN/07/AB/5678",reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 5, slotName: "Slot 5", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 6, slotName: "Slot 6", occupied: true, user: "User3", userVehicleNo: "TN/07/AB/9012",reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 7, slotName: "Slot 7", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 8, slotName: "Slot 8", occupied: true, user: "User4", userVehicleNo: "TN/07/AB/3456",reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 9, slotName: "Slot 9", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 10, slotName: "Slot 10", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 11, slotName: "Slot 11", occupied: true, user: "User5", userVehicleNo: "TN/07/AB/7890",reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 12, slotName: "Slot 12", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 13, slotName: "Slot 13", occupied: true, user: "User6", userVehicleNo: "TN/07/AB/2345",reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 14, slotName: "Slot 14", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 15, slotName: "Slot 15", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 16, slotName: "Slot 16", occupied: true, user: "User7", userVehicleNo: "TN/07/AB/6789",reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 17, slotName: "Slot 17", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 18, slotName: "Slot 18", occupied: true, user: "User8", userVehicleNo: "TN/07/AB/1122",reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 19, slotName: "Slot 19", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 20, slotName: "Slot 20", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null},
        ],
      },
    ],
  },
  {
    locationId: 2,
    location: "Chennai Mall 2",
    floors: [
      {
        floorId: 1,
        name: "Floor 1",
        slots: [
          { id: 1, slotName: "Slot 1", occupied: false, user: 1, userVehicleNo: "TN/07/AB/1234", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 2, slotName: "Slot 2", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 3, slotName: "Slot 3", occupied: false, user: 2, userVehicleNo: "TN/07/AB/5678", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 4, slotName: "Slot 4", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 5, slotName: "Slot 5", occupied: false, user: null, userVehicleNo: null, reserved: false, 
          reservedDetail: null,
           occupiedDt: null },
          { id: 6, slotName: "Slot 6", occupied: true, user: 3, userVehicleNo: "TN/07/AB/9012", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 7, slotName: "Slot 7", occupied: false, user: null, userVehicleNo: null, reserved: true, 
          reservedDetail: [{
            plan:"shortTerm",
            startDate:"2026-04-18",
            endDate:"",
            startTime:"17:50",
            endTime:"18:50",
            user: 2,
            userVehicleNo:"TN/07/AB/1234"
          }],
           occupiedDt: null },
          { id: 8, slotName: "Slot 8", occupied: true, user: 4, userVehicleNo: "TN/07/AB/3456", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 9, slotName: "Slot 9", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 10, slotName: "Slot 10", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 11, slotName: "Slot 11", occupied: true, user: 6, userVehicleNo: "TN/07/AB/7890", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 12, slotName: "Slot 12", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 13, slotName: "Slot 13", occupied: true, user: 6, userVehicleNo: "TN/07/AB/2345", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 14, slotName: "Slot 14", occupied: false, user: null, userVehicleNo: null, reserved: true, 
            reservedDetail: [{
            plan:"shortTerm",
            startDate:"2026-04-20",
            endDate:"",
            startTime:"17:50",
            endTime:"18:50",
            user: 1,
            userVehicleNo:"TN/07/AB/1236"
          }]
            , occupiedDt: null },
          { id: 15, slotName: "Slot 15", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 16, slotName: "Slot 16", occupied: true, user: 7, userVehicleNo: "TN/07/AB/6789", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 17, slotName: "Slot 17", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 18, slotName: "Slot 18", occupied: true, user: 8, userVehicleNo: "TN/07/AB/1122", reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 19, slotName: "Slot 19", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 20, slotName: "Slot 20", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
        ],
      },
      {
        floorId: 2,
        name: "Floor 2",
        slots: [
          { id: 1, slotName: "Slot 1", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 2, slotName: "Slot 2", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 3, slotName: "Slot 3", occupied: true, user: 2, userVehicleNo: "TN/07/AB/5678", reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 4, slotName: "Slot 4", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 5, slotName: "Slot 5", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 6, slotName: "Slot 6", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 7, slotName: "Slot 7", occupied: false, user: null, userVehicleNo: null, reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 8, slotName: "Slot 8", occupied: true, user: 4, userVehicleNo: "TN/07/AB/3456",reserved: false, reservedDetail: null, occupiedDt: null  },
          { id: 9, slotName: "Slot 9", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 10, slotName: "Slot 10", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 11, slotName: "Slot 11", occupied: true, user: 5, userVehicleNo: "TN/07/AB/7890" ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 12, slotName: "Slot 12", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 13, slotName: "Slot 13", occupied: true, user: 6, userVehicleNo: "TN/07/AB/2345" ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 14, slotName: "Slot 14", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 15, slotName: "Slot 15", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 16, slotName: "Slot 16", occupied: true, user: 7, userVehicleNo: "TN/07/AB/6789" ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 17, slotName: "Slot 17", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 18, slotName: "Slot 18", occupied: true, user: 8, userVehicleNo: "TN/07/AB/1122" ,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 19, slotName: "Slot 19", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
          { id: 20, slotName: "Slot 20", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
        ],
      }
      // ,
      // {
      //   floorId: 3,
      //   name: "Floor 3",
      //   slots: [
      //     { id: 2, slotName: "Slot 2", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 1, slotName: "Slot 1", occupied: true, user: 1, userVehicleNo: "TN/07/AB/1234",reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 4, slotName: "Slot 4", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 3, slotName: "Slot 3", occupied: true, user: 2, userVehicleNo: "TN/07/AB/5678",reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 5, slotName: "Slot 5", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 6, slotName: "Slot 6", occupied: true, user: 3, userVehicleNo: "TN/07/AB/9012",reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 7, slotName: "Slot 7", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 8, slotName: "Slot 8", occupied: true, user: 4, userVehicleNo: "TN/07/AB/3456",reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 9, slotName: "Slot 9", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 10, slotName: "Slot 10", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 11, slotName: "Slot 11", occupied: true, user: 5, userVehicleNo: "TN/07/AB/7890",reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 12, slotName: "Slot 12", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 13, slotName: "Slot 13", occupied: true, user: 6, userVehicleNo: "TN/07/AB/2345",reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 14, slotName: "Slot 14", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 15, slotName: "Slot 15", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 16, slotName: "Slot 16", occupied: true, user: 7, userVehicleNo: "TN/07/AB/6789",reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 17, slotName: "Slot 17", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 18, slotName: "Slot 18", occupied: true, user: 8, userVehicleNo: "TN/07/AB/1122",reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 19, slotName: "Slot 19", occupied: false, user: null, userVehicleNo: null,reserved: false, reservedDetail: null, occupiedDt: null },
      //     { id: 20, slotName: "Slot 20", occupied: false, user: null, userVehicleNo: null ,reserved: false, reservedDetail: null, occupiedDt: null},
      //   ],
      // },
    ],
  },
];

export default parkings;
